routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'dashboard'])->name('dashboard.app');

Route::get('forgot-password-verify/{token}', [App\Http\Controllers\LoginController::class, 'forgotPasswordValidate'])->name('forgot-password-verify');
Route::post('forgot-password', [App\Http\Controllers\LoginController::class, 'resetPassword'])->name('password-send-email');
Route::put('reset-password', [App\Http\Controllers\LoginController::class, 'updatePassword'])->name('reset-password');

/* ---------------- */
/* Global Functions */
/* ---------------- */
Route::group([
    'middleware' => ['auth']
],
    function () {
        Route::get('configuration/checkuniquefield', [App\Http\Controllers\System\UtilsController::class, 'checkUniqueField'])->name('checkuniquefield');
    }
);

/* ---------------- */
/* Routes admin */
/* ---------------- */
Route::group(['middleware' => ['auth']], function() {
    // Profile
    Route::get('profile/index', [App\Http\Controllers\admin\ProfileController::class, 'index'])->name('index.profile');
    Route::get('profile/edit', [App\Http\Controllers\admin\ProfileController::class, 'edit'])->name('edit.profile');
    Route::put('profile/update/{id}', [App\Http\Controllers\admin\ProfileController::class, 'update'])->name('update.profile');
    Route::put('profile/check/email', [App\Http\Controllers\admin\ProfileController::class, 'checkEmail'])->name('email_verify.profile');
    Route::get('profile/password', [App\Http\Controllers\admin\ProfileController::class, 'changePassword'])->name('change_password.profile');
    Route::put('profile/password/{id}', [App\Http\Controllers\admin\ProfileController::class, 'updatePassword'])->name('update_password.profile');

    // Menu
    Route::get('menus/data', [App\Http\Controllers\admin\MenuController::class, 'data'])->name('menus.data');
    Route::get('menus/enable_disable/{id}', [App\Http\Controllers\admin\MenuController::class, 'enableDisable'])->name('menus.enable_disable');
    Route::resource('menus', App\Http\Controllers\admin\MenuController::class, [
        'parameters' => ['menus' => 'id'],
        'names' => [
            'show' => 'show.menus',
            'store' => 'store.menus',
            'edit' => 'edit.menus',
            'update' => 'update.menus',
            'destroy' => 'destroy.menus'
        ]
    ]);

    // Roles
    Route::get('roles/data', [App\Http\Controllers\admin\RoleController::class, 'data'])->name('roles.data');
    Route::get('roles/enable_disable/{id}', [App\Http\Controllers\admin\RoleController::class, 'enableDisable'])->name('roles.enable_disable');
    Route::get('roles/permissions/{id}', [App\Http\Controllers\admin\RoleController::class, 'permissions'])->name('roles.permissions');
    Route::resource('roles', App\Http\Controllers\admin\RoleController::class, [
        'parameters' => ['roles' => 'id'],
        'names' => [
            'show' => 'show.roles',
            'store' => 'store.roles',
            'edit' => 'edit.roles',
            'update' => 'update.roles',
            'destroy' => 'destroy.roles'
        ]
    ]);

    // Usuarios
    Route::get('users/check_email', [App\Http\Controllers\admin\UserController::class, 'checkEmailExists'])->name('check_email.users');
    Route::get('users/data', [App\Http\Controllers\admin\UserController::class, 'data'])->name('users.data');
    Route::get('users/enable_disable/{id}', [App\Http\Controllers\admin\UserController::class, 'enableDisable'])->name('users.enable_disable');
    Route::resource('users', App\Http\Controllers\admin\UserController::class, [
        'parameters' => ['users' => 'id'],
        'names' => [
            'show' => 'show.users',
            'store' => 'store.users',
            'edit' => 'edit.users',
            'update' => 'update.users',
            'destroy' => 'destroy.users'
        ]
    ]);
});

app/Models/admin/Menu.php
<?php

namespace App\Models\admin;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'menus';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'header',
        'parent_id',
        'label',
        'slug',
        'permission',
        'icon',
        'weight',
        'status'
    ];
}

app/Http/Controllers/admin/MenuController.php
<?php

namespace App\Http\Controllers\admin;

use App\Repositories\admin\Menu\MenuInterface;
use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Yajra\DataTables\DataTables;
use Illuminate\Http\Request;
use App\Models\admin\Menu;
use Exception;
use Throwable;

class MenuController extends Controller
{
    protected $menu;

    public function __construct(
        MenuInterface $menu
    )
    {
        $this->menu = $menu;
        // Set permissions
        $this->middleware('permission:menu-list|menu-create|menu-edit|menu-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:menu-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:menu-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:menu-delete', ['only' => ['destroy']]);
        $this->middleware('permission:menu-show', ['only' => ['show']]);
        $this->middleware('permission:menu-delete', ['only' => ['delete']]);
    }

    /**
     * Index.
     *
     * @return JsonResponse
     */
    public function index()
    {
        try {
            $response['view'] = view('admin.menu.index', [
                'menus' => $this->menu->getAllData()
            ])->render();
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * Data.
     *
     * @param Request $request
     *
     * @return void
     * @throws Exception
     */
    public function data(Request $request)
    {
        try {
            if ($request->ajax()) {
                $user = currentUser();
                $data = Menu::all()->sortBy('weight');
                $actions = [];
                if ($user->can('menu-edit')) {
                    $actions['edit'] = [
                        'route' => 'edit.menus',
                        'tooltip' => __('menu.labels.edit')
                    ];
                }
                if ($user->can('menu-show')) {
                    $actions['eye'] = [
                        'route' => 'show.menus',
                        'tooltip' => __('menu.labels.show')
                    ];
                }
                if ($user->can('menu-delete')) {
                    $actions['trash'] = [
                        'route' => 'destroy.menus',
                        'tooltip' => __('app.labels.delete'),
                        'confirm_message' => __('menu.messages.confirm.delete'),
                        'method' => 'delete',
                        'btn_class' => 'btn-danger'
                    ];
                }
                $disable = true;
                if ($user->can('menu-enable_disable')) {
                    $disable = false;
                }
                return Datatables::of($data)
                    ->setRowId('id')
                    ->addColumn('actions', function ($entity) use ($actions) {
                        return view('layout.partial.datatable_action', [
                            'entity' => $entity,
                            'actions' => $actions
                        ]);
                    })
                    ->addColumn('enabled', function ($entity) use ($user, $disable) {
                        $checked = $entity->status ? 'checked' : '';
                        $is_disable = $disable ? 'disabled' : '';
                        return "<div class='form-group text-center'>
                                    <div class='custom-control custom-switch'>
                                        <input type='checkbox' class='custom-control-input' id='customSwitch" . $entity->id . "' " . $checked . " " . $is_disable . ">
                                        <label class='custom-control-label' for='customSwitch" . $entity->id . "'></label>
                                    </div>
                                </div>";
                    })
                    ->editColumn('icon', function ($entity) {
                        $icon = $entity->icon;
                        return "<i class='fa fa-{$icon}' aria-hidden='true'></i>";
                    })
                    ->rawColumns(['actions', 'icon', 'enabled'])
                    ->make(true);
            }
        } catch (Throwable $e) {
            return datatableEmptyResponse($e);
        }
    }

    /**
     * Create.
     *
     * @return JsonResponse
     */
    public function create()
    {
        try {
            $response['modal'] = view('admin.menu.create')->render();
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * Store.
     *
     * @param Request $request
     * @return JsonResponse
     */
    public function store(Request $request)
    {
        try {
            $data = $request->only([
                'header',
                'label',
                'slug',
                'icon',
                'weight'
            ]);
            $this->menu->storeOrUpdate($id = null, $data);
            $response = [
                'view' => view('admin.menu.index', [
                    'reload' => true
                ])->render(),
                'message' => [
                    'title' => __('app.labels.done'),
                    'type' => 'success',
                    'text' => __('menu.messages.success.created')
                ]
            ];
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * Edit
     *
     * @param int $id
     * @return JsonResponse
     */
    public function edit(int $id)
    {
        try {
            $entity = Menu::find($id);
            $response['modal'] = view('admin.menu.update', [
                'entity' => $entity
            ])->render();
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * @param int $id
     * @param Request $request
     * @return JsonResponse
     */
    public function update(int $id, Request $request)
    {
        try {
            $data = $request->only([
                'header',
                'label',
                'slug',
                'icon',
                'weight'
            ]);
            $this->menu->storeOrUpdate($id, $data);
            $response = [
                'view' => view('admin.menu.index', [
                    'reload' => true
                ])->render(),
                'message' => [
                    'title' => __('app.labels.done'),
                    'type' => 'success',
                    'text' => __('menu.messages.success.updated')
                ]
            ];
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * Show
     *
     * @param int $id
     * @return JsonResponse
     */
    public function show(int $id)
    {
        try {
            $entity = Menu::find($id);
            $response['modal'] = view('admin.menu.show', [
                'entity' => $entity
            ])->render();
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * Enable or Disable this model.
     *
     * @param $id
     *
     * @return JsonResponse
     */
    public function enableDisable($id)
    {
        try {
            $entity = Menu::find($id);
            if (!$entity) {
                throw new Exception(__('menu.messages.exceptions.not_found'), 1000);
            }
            $entity->status = !$entity->status;
            if (!$this->menu->changeStatus($entity)) {
                throw new Exception(__('menu.messages.errors.update'), 1000);
            }
            $response = [
                'view' => view('admin.menu.index', [
                    'reload' => true
                ])->render(),
                'message' => [
                    'title' => __('app.labels.done'),
                    'type' => 'success',
                    'text' => __('menu.messages.success.updated')
                ]
            ];
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * Destroy.
     *
     * @param $id
     *
     * @return JsonResponse
     */
    public function destroy($id)
    {
        try {
            $response = $this->menu->destroy($id);
            if ($response) {
                $response = [
                    'view' => view('admin.menu.index', [
                        'reload' => true
                    ])->render(),
                    'message' => [
                        'title' => __('app.labels.done'),
                        'type' => 'success',
                        'text' => __('menu.messages.success.deleted')
                    ]
                ];
            } else {
                $response = [
                    'view' => view('admin.menu.index')->render(),
                    'message' => [
                        'title' => __('app.labels.error'),
                        'type' => 'alert',
                        'text' => __('menu.messages.alert.delete')
                    ]
                ];
            }
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }
}

resources/views/admin/menu/create.blade.php
@can('menu-create')
<div class="modal-header">
    <h4 class="modal-title">{{ __('menu.labels.create') }}</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form id="createMenu" role="form" action="{{ route('store.menus') }}" method="post" class="form-horizontal form-label-left">
        @csrf
        <div class="card-body">
            <div class="form-group row">
                <label for="header" class="col-sm-2 col-form-label">
                    {{ __('menu.labels.header') }}
                </label>
                <div class="col-sm-10">
                    <input type="text" name="header" class="form-control" id="header" placeholder="{{ __('menu.placeholders.header') }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="label" class="col-sm-2 col-form-label">
                    {{ __('menu.labels.label') }} <span class="text-danger">*</span>
                </label>
                <div class="col-sm-10">
                    <input type="text" name="label" class="form-control" id="label" placeholder="{{ __('menu.placeholders.label') }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="slug" class="col-sm-2 col-form-label">
                    {{ __('menu.labels.slug') }}
                </label>
                <div class="col-sm-10">
                    <input type="text" name="slug" class="form-control" id="slug" placeholder="{{ __('menu.placeholders.slug') }}">
                </div>
            </div>
            <div class="form-group input-group-sm row">
                <label for="icon" class="col-sm-2 col-form-label">
                    {{ __('menu.labels.icon') }}
                </label>
                <div class="col-sm-10">
                    <input type="text" name="icon" class="form-control" id="icon" placeholder="{{ __('menu.placeholders.icon') }}">
                </div>
            </div>
            <div class="form-group input-group-sm row">
                <label for="weight" class="col-sm-2 col-form-label">
                    {{ __('menu.labels.weight') }} <span class="text-danger">*</span>
                </label>
                <div class="col-sm-10">
                    <input type="text" name="weight" class="form-control" id="weight" placeholder="{{ __('menu.placeholders.weight') }}">
                </div>
            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <div class="row">
                <div class="col text-center">
                    <button type="button" class="btn btn-default btn-sm"
                            data-dismiss="modal">{{ __('app.labels.close') }}</button>
                    <button type="submit"
                            class="btn btn-primary btn-sm">{{ __('app.labels.save') }}</button>
                </div>
            </div>
        </div>
    </form>
</div>

<script>
    $(function () {
        const $form = $('#createMenu')

        $validateDefaults.rules = {
            label: {
                required: true,
                remote: {
                    url: "{!! route('checkuniquefield') !!}",
                    data: {
                        fieldName: 'label',
                        fieldValue: () => {
                            return $('#label', $form).val()
                        },
                        model: 'App\\Models\\admin\\Menu'
                    }
                }
            },
            weight: {
                required: true
            }
        }

        $validateDefaults.messages = {
            label: {
                remote: '{!! trans('menu.messages.validation.name') !!}'
            }
        }

        // J Validator
        $form.validate($validateDefaults);
        $form.ajaxForm($.extend(false, $formAjaxDefaults, {
            success: (response) => {
                processResponse(response, null, () => {
                    $modal.modal('hide')
                })
            }
        }))
    })
</script>
@else
    @include('errors.403_modal')
@endcan

resources/views/admin/menu/index.blade.php
@can('menu-list')
    <!-- Navbar content -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{ __('menu.title') }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">{{ __('app.labels.administration') }}</a></li>
                        <li class="breadcrumb-item active">{{ __('menu.title') }}</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- COLOR PALETTE -->
            <div class="card card-default color-palette-box">
                <div class="card-header">
                    <h3 class="card-title">
                        <i class="fas fa-list"></i>
                        {{ __('menu.title') }}
                    </h3>
                    @can('menu-create')
                        <a href="{{ route('menus.create') }}"
                           class="btn btn-primary bg-gradient-primary btn-sm float-right ajaxify">
                            {{ __('menu.labels.create') }}
                        </a>
                    @endcan
                </div>
                <!-- /.card-header -->
                <!-- .card-body -->
                <div class="card-body">
                    <table id="menu_tb" class="table table-striped table-bordered" width="100%">
                        <thead>
                        <tr>
                            <th></th>
                            <th>label</th>
                            <th>header</th>
                            <th>slug</th>
                            <th>icon</th>
                            <th>weight</th>
                            <th>Enable</th>
                            <th>{{ __('app.labels.actions') }}</th>
                        </tr>
                        </thead>
                    </table>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">&nbsp&nbsp</div>
            </div>
        </div>
    </section>
    <script>
        $(function () {
            let datatable = $('#menu_tb').DataTable({
                responsive: true,
                ajax: "{{ route('menus.data') }}",
                columns: [
                    {data: 'id', name: 'id', visible: false, sortable: false, searchable: false, width: '0'},
                    {data: 'label', name: 'label', width: '20%', sortable: true, searchable: true},
                    {data: 'header', name: 'header', width: '20%', sortable: true, searchable: true},
                    {data: 'slug', name: 'slug', width: '15%', sortable: true, searchable: true},
                    {data: 'icon', name: 'icon', width: '10%', sortable: true, searchable: true},
                    {data: 'weight', name: 'weight', width: '10%', sortable: true, searchable: true},
                    {data: 'enabled', width: '10%', searchable: false, sortable: false},
                    {data: 'actions', width: '15%', sortable: false, searchable: false, class: 'text-center'}
                ]
            })

            $('#menu_tb').on('click', 'input[type="checkbox"]', function (e) {
                e.preventDefault()
                let confirmMessage = $(this).is(':checked') ? '{{ __('menu.messages.confirm.status_on') }}' : '{{ __('menu.messages.confirm.status_off') }}'
                let element = $(this)
                confirmModal(confirmMessage, function () {
                    let id = element.closest('tr').attr('id')
                    let url = "{!! route('menus.enable_disable', ['id' => '__ID__']) !!}"
                    url = url.replace('__ID__', id)
                    pushRequest(url, null, function () {
                        datatable.draw()
                    }, 'get', null)
                })
            })

            @if(isset($reload) && $reload)
                confirmModal('{{ __('menu.messages.confirm.reload') }}', () => {
                    location.reload()
                })
            @endif
        })
    </script>
@else
    @include('errors.403')
@endcan

resources/views/admin/menu/show.blade.php
@can('menu-show')
<div class="modal-header">
    <h4 class="modal-title">{{ __('menu.labels.show') }}</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form id="createMenu" role="form" method="post" class="form-horizontal form-label-left">
        <div class="card-body">
            <div class="form-group row">
                <label for="header" class="col-sm-2 col-form-label">{{ __('menu.labels.header') }}</label>
                <div class="col-sm-10">
                    <input type="text" name="header" class="form-control" id="header" placeholder="{{ __('menu.placeholders.header') }}" value="{{ $entity->header }}" disabled>
                </div>
            </div>
            <div class="form-group row">
                <label for="label" class="col-sm-2 col-form-label">{{ __('menu.labels.label') }}</label>
                <div class="col-sm-10">
                    <input type="text" name="label" class="form-control" id="label" placeholder="{{ __('menu.placeholders.label') }}" value="{{ $entity->label }}" disabled>
                </div>
            </div>
            <div class="form-group row">
                <label for="slug" class="col-sm-2 col-form-label">{{ __('menu.labels.slug') }}</label>
                <div class="col-sm-10">
                    <input type="text" name="slug" class="form-control" id="slug" placeholder="{{ __('menu.placeholders.slug') }}" value="{{ $entity->slug }}" disabled>
                </div>
            </div>
            <div class="form-group input-group-sm row">
                <label for="icon" class="col-sm-2 col-form-label">{{ __('menu.labels.icon') }}</label>
                <div class="col-sm-10">
                    <i class='fa fa-{{ $entity->icon }}' aria-hidden='true'></i>
                </div>
            </div>
            <div class="form-group input-group-sm row">
                <label for="weight" class="col-sm-2 col-form-label">{{ __('menu.labels.weight') }}</label>
                <div class="col-sm-10">
                    <input type="text" name="weight" class="form-control" id="weight" placeholder="{{ __('menu.placeholders.weight') }}" value="{{ $entity->weight }}" disabled>
                </div>
            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <div class="row">
                <div class="col text-center">
                    <button type="button" class="btn btn-default btn-sm"
                            data-dismiss="modal">{{ __('app.labels.close') }}</button>
                </div>
            </div>
        </div>
    </form>
</div>
@else
    @include('errors.403_modal')
@endcan

resources/views/admin/menu/update.blade.php
@can('menu-edit')
<div class="modal-header">
    <h4 class="modal-title">{{ __('menu.labels.edit') }}</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form id="updateMenu" role="form" action="{{ route('update.menus', ['id' => $entity->id]) }}" method="post" class="form-horizontal form-label-left">
        @csrf
        @method('PUT')
        <div class="card-body">
            <div class="form-group row">
                <label for="header" class="col-sm-2 col-form-label">
                    {{ __('menu.labels.header') }}
                </label>
                <div class="col-sm-10">
                    <input type="text" name="header" class="form-control" id="header" placeholder="{{ __('menu.placeholders.header') }}" value="{{ $entity->header }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="label" class="col-sm-2 col-form-label">
                    {{ __('menu.labels.label') }} <span class="text-danger">*</span>
                </label>
                <div class="col-sm-10">
                    <input type="text" name="label" class="form-control" id="label" placeholder="{{ __('menu.placeholders.label') }}" value="{{ $entity->label }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="slug" class="col-sm-2 col-form-label">
                    {{ __('menu.labels.slug') }}
                </label>
                <div class="col-sm-10">
                    <input type="text" name="slug" class="form-control" id="slug" placeholder="{{ __('menu.placeholders.slug') }}" value="{{ $entity->slug }}">
                </div>
            </div>
            <div class="form-group input-group-sm row">
                <label for="icon" class="col-sm-2 col-form-label">
                    {{ __('menu.labels.icon') }}
                </label>
                <div class="col-sm-10">
                    <input type="text" name="icon" class="form-control" id="icon" placeholder="{{ __('menu.placeholders.icon') }}" value="{{ $entity->icon }}">
                </div>
            </div>
            <div class="form-group input-group-sm row">
                <label for="weight" class="col-sm-2 col-form-label">
                    {{ __('menu.labels.weight') }} <span class="text-danger">*</span>
                </label>
                <div class="col-sm-10">
                    <input type="text" name="weight" class="form-control" id="weight" placeholder="{{ __('menu.placeholders.weight') }}" value="{{ $entity->weight }}">
                </div>
            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <div class="row">
                <div class="col text-center">
                    <button type="button" class="btn btn-default btn-sm"
                            data-dismiss="modal">{{ __('app.labels.close') }}</button>
                    <button type="submit"
                            class="btn btn-primary btn-sm">{{ __('app.labels.save') }}</button>
                </div>
            </div>
        </div>
    </form>
</div>

<script>
    $(function () {
        const $form = $('#updateMenu')

        $validateDefaults.rules = {
            label: {
                required: true,
                remote: {
                    url: "{!! route('checkuniquefield') !!}",
                    data: {
                        fieldName: 'label',
                        fieldValue: () => {
                            return $('#label', $form).val();
                        },
                        model: 'App\\Models\\admin\\Menu',
                        current: '{{ $entity->id }}'
                    }
                }
            },
            weight: {
                required: true
            }
        }

        $validateDefaults.messages = {
            label: {
                remote: '{!! trans('menu.messages.validation.name') !!}'
            }
        }

        // J Validator
        $form.validate($validateDefaults);
        $form.ajaxForm($.extend(false, $formAjaxDefaults, {
            success: (response) => {
                processResponse(response, null, () => {
                    $modal.modal('hide')
                })
            }
        }))
    })
</script>
@else
    @include('errors.403_modal')
@endcan