routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'dashboard'])->name('dashboard.app');

Route::get('forgot-password-verify/{token}', [App\Http\Controllers\LoginController::class, 'forgotPasswordValidate'])->name('forgot-password-verify');
Route::post('forgot-password', [App\Http\Controllers\LoginController::class, 'resetPassword'])->name('password-send-email');
Route::put('reset-password', [App\Http\Controllers\LoginController::class, 'updatePassword'])->name('reset-password');

/* ---------------- */
/* Global Functions */
/* ---------------- */
Route::group([
    'middleware' => ['auth']
],
    function () {
        Route::get('configuration/checkuniquefield', [App\Http\Controllers\System\UtilsController::class, 'checkUniqueField'])->name('checkuniquefield');
    }
);

/* ---------------- */
/* Routes admin */
/* ---------------- */
Route::group(['middleware' => ['auth']], function() {
    // Profile
    Route::get('profile/index', [App\Http\Controllers\admin\ProfileController::class, 'index'])->name('index.profile');
    Route::get('profile/edit', [App\Http\Controllers\admin\ProfileController::class, 'edit'])->name('edit.profile');
    Route::put('profile/update/{id}', [App\Http\Controllers\admin\ProfileController::class, 'update'])->name('update.profile');
    Route::put('profile/check/email', [App\Http\Controllers\admin\ProfileController::class, 'checkEmail'])->name('email_verify.profile');
    Route::get('profile/password', [App\Http\Controllers\admin\ProfileController::class, 'changePassword'])->name('change_password.profile');
    Route::put('profile/password/{id}', [App\Http\Controllers\admin\ProfileController::class, 'updatePassword'])->name('update_password.profile');

    // Menu
    Route::get('menus/data', [App\Http\Controllers\admin\MenuController::class, 'data'])->name('menus.data');
    Route::get('menus/enable_disable/{id}', [App\Http\Controllers\admin\MenuController::class, 'enableDisable'])->name('menus.enable_disable');
    Route::resource('menus', App\Http\Controllers\admin\MenuController::class, [
        'parameters' => ['menus' => 'id'],
        'names' => [
            'show' => 'show.menus',
            'store' => 'store.menus',
            'edit' => 'edit.menus',
            'update' => 'update.menus',
            'destroy' => 'destroy.menus'
        ]
    ]);

    // Roles
    Route::get('roles/data', [App\Http\Controllers\admin\RoleController::class, 'data'])->name('roles.data');
    Route::get('roles/enable_disable/{id}', [App\Http\Controllers\admin\RoleController::class, 'enableDisable'])->name('roles.enable_disable');
    Route::get('roles/permissions/{id}', [App\Http\Controllers\admin\RoleController::class, 'permissions'])->name('roles.permissions');
    Route::resource('roles', App\Http\Controllers\admin\RoleController::class, [
        'parameters' => ['roles' => 'id'],
        'names' => [
            'show' => 'show.roles',
            'store' => 'store.roles',
            'edit' => 'edit.roles',
            'update' => 'update.roles',
            'destroy' => 'destroy.roles'
        ]
    ]);

    // Usuarios
    Route::get('users/check_email', [App\Http\Controllers\admin\UserController::class, 'checkEmailExists'])->name('check_email.users');
    Route::get('users/data', [App\Http\Controllers\admin\UserController::class, 'data'])->name('users.data');
    Route::get('users/enable_disable/{id}', [App\Http\Controllers\admin\UserController::class, 'enableDisable'])->name('users.enable_disable');
    Route::resource('users', App\Http\Controllers\admin\UserController::class, [
        'parameters' => ['users' => 'id'],
        'names' => [
            'show' => 'show.users',
            'store' => 'store.users',
            'edit' => 'edit.users',
            'update' => 'update.users',
            'destroy' => 'destroy.users'
        ]
    ]);
});

app/Models/admin/Role.php
<?php

namespace App\Models\admin;

use Illuminate\Database\Eloquent\Model;
use App\Models\User;

class Role extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'roles';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'guard_name',
        'description',
        'status'
    ];

    const ROLE_ADMIN = 1;
    const ROLE_DEVELOP = 2;
    const ROLE_USER = 3;

    /**
     * Get the post's image.
     */
    public function user()
    {
        return $this->morphOne(User::class, 'model_type');
    }
}

app/Http/Controllers/admin/RoleController.php
<?php

namespace App\Http\Controllers\admin;

use App\Repositories\admin\Role\RoleInterface;
use Spatie\Permission\Models\Permission;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;
use Illuminate\Http\JsonResponse;
use Yajra\DataTables\DataTables;
use Illuminate\Http\Request;
use Exception;
use Throwable;

class RoleController extends Controller
{
    protected $role;

    public function __construct(RoleInterface $role)
    {
        $this->role = $role;
        // Set permissions
        $this->middleware('permission:role-list|role-create|role-edit|role-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:role-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:role-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:role-delete', ['only' => ['destroy']]);
        $this->middleware('permission:role-show', ['only' => ['show']]);
        $this->middleware('permission:role-delete', ['only' => ['delete']]);
        $this->middleware('permission:role-permissions', ['only' => ['permissions']]);
    }

    /**
     * Index.
     *
     * @return JsonResponse
     */
    public function index()
    {
        try {
            $response['view'] = view('admin.role.index', [
                'roles' => $this->role->getAllData()
            ])->render();
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * Data.
     *
     * @param Request $request
     *
     * @return void
     */
    public function data(Request $request)
    {
        try {
            if ($request->ajax()) {
                $user = currentUser();
                $actions = [];
                if ($user->can('role-edit')) {
                    $actions['edit'] = [
                        'route' => 'edit.roles',
                        'tooltip' => __('role.labels.edit')
                    ];
                }
                if ($user->can('role-show')) {
                    $actions['eye'] = [
                        'route' => 'show.roles',
                        'tooltip' => __('role.labels.show')
                    ];
                }
                if ($user->can('role-delete')) {
                    $actions['trash'] = [
                        'route' => 'destroy.roles',
                        'tooltip' => __('app.labels.delete'),
                        'confirm_message' => __('role.messages.confirm.delete'),
                        'method' => 'delete',
                        'btn_class' => 'btn-danger'
                    ];
                }
                $disable = true;
                if ($user->can('role-enable_disable')) {
                    $disable = false;
                }
                if ($user->can('role-permissions')) {
                    $actions['list'] = [
                        'route' => 'roles.permissions',
                        'tooltip' => __('role.labels.permissions')
                    ];
                }
                $data = Role::all()->sortBy('weight');
                return Datatables::of($data)
                    ->setRowId('id')
                    ->addColumn('actions', function ($entity) use ($actions) {
                        return view('layout.partial.datatable_action', [
                            'entity' => $entity,
                            'actions' => $actions
                        ]);
                    })
                    ->addColumn('enabled', function ($entity) use ($user, $disable) {
                        $checked = $entity->status ? 'checked' : '';
                        $is_disable = $disable ? 'disabled' : '';
                        return "<div class='form-group text-center'>
                                    <div class='custom-control custom-switch'>
                                        <input type='checkbox' class='custom-control-input datatable' id='customSwitch" . $entity->id . "' " . $checked . " " . $is_disable . ">
                                        <label class='custom-control-label' for='customSwitch" . $entity->id . "'></label>
                                    </div>
                                </div>";
                    })
                    ->editColumn('icon', function ($entity) {
                        $icon = $entity->icon;
                        return "<i class='fa fa-{$icon}' aria-hidden='true'></i>";
                    })
                    ->rawColumns(['actions', 'icon', 'enabled'])
                    ->make(true);
            }
        } catch (Throwable $e) {
            return datatableEmptyResponse($e);
        }
    }

    /**
     * Create.
     *
     * @return JsonResponse
     */
    public function create()
    {
        try {
            $response['modal'] = view('admin.role.create')->render();
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * Store.
     *
     * @param Request $request
     * @return JsonResponse
     */
    public function store(Request $request)
    {
        try {
            $data = $request->only([
                'name',
                'description'
            ]);
            $this->role->storeOrUpdate($id = null, $data);
            $response = [
                'view' => view('admin.role.index')->render(),
                'message' => [
                    'title' => __('app.labels.done'),
                    'type' => 'success',
                    'text' => __('role.messages.success.created')
                ]
            ];
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * Edit
     *
     * @param int $id
     * @return JsonResponse
     */
    public function edit(int $id)
    {
        try {
            $entity = Role::find($id);
            $response['modal'] = view('admin.role.update', [
                'entity' => $entity
            ])->render();
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * @param int $id
     * @param Request $request
     * @return JsonResponse
     */
    public function update(int $id, Request $request)
    {
        try {
            $data = $request->only([
                'name',
                'permission',
                'description'
            ]);
            $this->role->storeOrUpdate($id, $data);
            $response = [
                'view' => view('admin.role.index')->render(),
                'message' => [
                    'title' => __('app.labels.done'),
                    'type' => 'success',
                    'text' => __('role.messages.success.updated')
                ]
            ];
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * Show
     *
     * @param int $id
     * @return JsonResponse
     */
    public function show(int $id)
    {
        try {
            $entity = Role::find($id);
            $response['modal'] = view('admin.role.show', [
                'entity' => $entity
            ])->render();
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * Enable or Disable this model.
     *
     * @param $id
     *
     * @return JsonResponse
     */
    public function enableDisable($id)
    {
        try {
            $entity = Role::find($id);
            if (!$entity) {
                throw new Exception(__('role.messages.exceptions.not_found'), 1000);
            }
            if (count($entity->users)) {
                $response['message'] = [
                    'title' => __('app.labels.warning'),
                    'type' => 'warning',
                    'text' => __('role.messages.validation.has_users')
                ];
            } else {
                $entity->status = !$entity->status;
                if (!$this->role->changeStatus($entity)) {
                    throw new Exception(__('role.messages.errors.update'), 1000);
                }
                $response['message'] = [
                    'title' => __('app.labels.done'),
                    'type' => 'success',
                    'text' => __('role.messages.success.updated')
                ];
            }
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * Destroy.
     *
     * @param $id
     *
     * @return JsonResponse
     */
    public function destroy($id)
    {
        try {
            $entity = Role::find($id);
            if (!$entity) {
                throw new Exception(__('role.messages.exceptions.not_found'), 1000);
            }
            if (count($entity->users)) {
                $response = [
                    'view' => view('admin.role.index')->render(),
                    'message' => [
                        'title' => __('app.labels.warning'),
                        'type' => 'warning',
                        'text' => __('role.messages.validation.has_users')
                    ]
                ];
            } else {
                $response = $this->role->destroy($id);
                if ($response) {
                    $response = [
                        'view' => view('admin.role.index')->render(),
                        'message' => [
                            'title' => __('app.labels.done'),
                            'type' => 'success',
                            'text' => __('role.messages.success.deleted')
                        ]
                    ];

resources/views/admin/role/create.blade.php
@can('role-create')
<div class="modal-header">
    <h4 class="modal-title">{{ __('role.labels.create') }}</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form id="createMenu" role="form" action="{{ route('store.roles') }}" method="post" class="form-horizontal form-label-left">
        @csrf
        <div class="card-body">
            <div class="form-group row">
                <label for="name" class="col-sm-2 col-form-label">
                    {{ __('role.labels.name') }} <span class="text-danger">*</span>
                </label>
                <div class="col-sm-10">
                    <input type="text" name="name" class="form-control" id="name" maxlength="250" placeholder="{{ __('role.placeholders.name') }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="description" class="col-sm-2 col-form-label">
                    {{ __('role.labels.description') }} <span class="text-danger">*</span>
                </label>
                <div class="col-sm-10">
                    <input type="text" name="description" class="form-control" id="description" maxlength="250" placeholder="{{ __('role.placeholders.description') }}">
                </div>
            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <div class="row">
                <div class="col text-center">
                    <button type="button" class="btn btn-default btn-sm"
                            data-dismiss="modal">{{ __('app.labels.close') }}</button>
                    <button type="submit"
                            class="btn btn-primary btn-sm">{{ __('app.labels.save') }}</button>
                </div>
            </div>
        </div>
    </form>
</div>

<script>
    $(function () {
        const $form = $('#createMenu')

        $validateDefaults.rules = {
            name: {
                required: true,
                minlength: 2,
                remote: {
                    url: "{!! route('checkuniquefield') !!}",
                    data: {
                        fieldName: 'name',
                        fieldValue: () => {
                            return $('#name', $form).val()
                        },
                        model: 'App\\Models\\admin\\Role'
                    }
                }
            },
            description: {
                required: true
            }
        }

        $validateDefaults.messages = {
            name: {
                remote: '{!! trans('role.messages.validation.name') !!}'
            }
        }

        // J Validator
        $form.validate($validateDefaults);
        $form.ajaxForm($.extend(false, $formAjaxDefaults, {
            success: (response) => {
                processResponse(response, null, () => {
                    $modal.modal('hide')
                })
            }
        }))
    })
</script>
@else
    @include('errors.403_modal')
@endcan

resources/views/admin/role/index.blade.php
@can('role-list')
    <!-- Navbar content -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{ __('role.title') }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">{{ __('app.labels.administration') }}</a></li>
                        <li class="breadcrumb-item active">{{ __('role.title') }}</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- COLOR PALETTE -->
            <div class="card card-default color-palette-box">
                <div class="card-header">
                    <h3 class="card-title">
                        <i class="fas fa-address-book"></i>
                        {{ __('role.title') }}
                    </h3>
                    @can('role-create')
                        <a href="{{ route('roles.create') }}"
                           class="btn btn-primary bg-gradient-primary btn-sm float-right ajaxify">
                            {{ __('role.labels.create') }}
                        </a>
                    @endcan
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="role_tb" class="table table-striped table-bordered" width="100%">
                        <thead>
                        <tr>
                            <th></th>
                            <th>{{ __('role.labels.name') }}</th>
                            <th>{{ __('role.labels.description') }}</th>
                            <th>{{ __('role.labels.status') }}</th>
                            <th>{{ __('app.labels.actions') }}</th>
                        </tr>
                        </thead>
                    </table>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">&nbsp&nbsp</div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>

    <script>
        $(function () {
            let datatable = $('#role_tb').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('roles.data') }}",
                columns: [
                    {data: 'id', name: 'id', visible: false, sortable: false, searchable: false, width: '0'},
                    {data: 'name', name: 'name', width: '20%', sortable: true, searchable: true},
                    {data: 'description', name: 'name', width: '40%', sortable: true, searchable: true},
                    {data: 'enabled', width: '20%', searchable: false, sortable: false},
                    {data: 'actions', width: '20%', sortable: false, searchable: false, class: 'text-center'}
                ]
            })

            $('#role_tb').on('click', 'input[type="checkbox"]', function (e) {
                e.preventDefault()
                let confirmMessage = $(this).is(':checked') ? '{{ __('role.messages.confirm.status_on') }}' : '{{ __('role.messages.confirm.status_off') }}'
                let element = $(this)
                confirmModal(confirmMessage, function () {
                    let id = element.closest('tr').attr('id')
                    let url = "{!! route('roles.enable_disable', ['id' => '__ID__']) !!}"
                    url = url.replace('__ID__', id)
                    pushRequest(url, null, function () {
                        datatable.draw()
                    }, 'get', null)
                })
            })
        })
    </script>
@else
    @include('errors.403')
@endcan

resources/views/admin/role/permissions.blade.php
@can('role-permissions')
<div class="modal-header">
    <h4 class="modal-title">{{ __('role.labels.permissions') }}</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form id="updateMenu" role="form" action="{{ route('update.roles', ['id' => $entity->id]) }}" method="post" class="form-horizontal form-label-left">
        @csrf
        @method('PUT')
        <div class="card-body">
            <div class="form-group row">
                <label for="header" class="col-sm-2 col-form-label">{{ __('role.labels.name') }}</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control"placeholder="{{ __('role.placeholders.name') }}" value="{{ $entity->description }}" disabled>
                </div>
            </div>
            <div class="row h-100 justify-content-center align-items-center">
                <h3 class="card-title text-center">
                    <strong>{{ __('role.labels.permissions') }}</strong>
                </h3>
            </div>
            <div class="form-group row">
                <div class="form-group">
                    @foreach($permission as $value)
                            @if(!$value->parent_id)
                                <div class="custom-control custom-switch custom-switch-on-success">
                                    <input type="checkbox" class="custom-control-input select-all" attr_id="{{ $value->id }}" name="permission[]" id="permission-{{ $value->id }}" value="{{ $value->id }}" @if(in_array($value->id, $rolePermissions)) checked @endif>
                                    <label class="custom-control-label" for="permission-{{ $value->id }}">{{ $value->description }}</label>
                                </div>
                            @else
                                <div class="custom-control custom-switch">
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    <input type="checkbox" class="custom-control-input select-individual attr_parent_id_{{ $value->parent_id }}" attr_parent_id="{{ $value->parent_id }}" name="permission[]" id="permission-{{ $value->id }}" value="{{ $value->id }}" @if(in_array($value->id, $rolePermissions)) checked @endif>
                                    <label class="custom-control-label" for="permission-{{ $value->id }}">{{ $value->description }}</label>
                                </div>
                            @endif
                    @endforeach
                </div>
            </div>

        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <div class="row">
                <div class="col text-center">
                    <button type="button" class="btn btn-default btn-sm"
                            data-dismiss="modal">{{ __('app.labels.close') }}</button>
                    <button type="submit"
                            class="btn btn-primary btn-sm">{{ __('app.labels.save') }}</button>
                </div>
            </div>
        </div>
    </form>
</div>

<script>
    $(function () {
        const $form = $('#updateMenu')

        // J Validator
        $form.validate($validateDefaults);
        $form.ajaxForm($.extend(false, $formAjaxDefaults, {
            success: (response) => {
                processResponse(response, null, () => {
                    $modal.modal('hide')
                })
            }
        }))

        // select all by principal
        $('.select-all').on('change', (e) => {
            e.preventDefault()
            let checked = $(e.target).is(':checked')
            let id = e.target.attributes.attr_id.value
            if (checked) {
                $(`.attr_parent_id_${id}`).prop("checked", true)
            } else {
                $(`.attr_parent_id_${id}`).prop("checked", false)
            }
        })

        // select principal by select all
        $('.select-individual').on('change', (e) => {
            let id = e.target.attributes.attr_parent_id.value
            if ($(`.attr_parent_id_${id}:checked`).length == $(`.attr_parent_id_${id}`).length) {
                $(`#permission-${id}`).prop("checked", true)
            } else {
                $(`#permission-${id}`).prop("checked", false)
            }
        })

    })
</script>
@else
    @include('errors.403_modal')
@endcan

resources/views/admin/role/show.blade.php
@can('role-show')
<div class="modal-header">
    <h4 class="modal-title">{{ __('role.labels.show') }}</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form id="createMenu" role="form" method="post" class="form-horizontal form-label-left">
        <div class="card-body">
            <div class="form-group row">
                <label for="header" class="col-sm-2 col-form-label">{{ __('role.labels.name') }}</label>
                <div class="col-sm-10">
                    <input type="text" name="name" class="form-control" id="name" placeholder="{{ __('role.placeholders.name') }}" value="{{ $entity->name }}" disabled>
                </div>
            </div>
            <div class="form-group row">
                <label for="header" class="col-sm-2 col-form-label">{{ __('role.labels.description') }}</label>
                <div class="col-sm-10">
                    <input type="text" name="description" class="form-control" id="description" placeholder="{{ __('role.placeholders.description') }}" value="{{ $entity->description }}" disabled>
                </div>
            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <div class="row">
                <div class="col text-center">
                    <button type="button" class="btn btn-default btn-sm"
                            data-dismiss="modal">{{ __('app.labels.close') }}</button>
                </div>
            </div>
        </div>
    </form>
</div>
@else
    @include('errors.403_modal')
@endcan

resources/views/admin/role/update.blade.php
@can('role-edit')
<div class="modal-header">
    <h4 class="modal-title">{{ __('role.labels.edit') }}</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form id="updateMenu" role="form" action="{{ route('update.roles', ['id' => $entity->id]) }}" method="post" class="form-horizontal form-label-left">
        @csrf
        @method('PUT')
        <div class="card-body">
            <div class="form-group row">
                <label for="name" class="col-sm-2 col-form-label">
                    {{ __('role.labels.name') }} <span class="text-danger">*</span>
                </label>
                <div class="col-sm-10">
                    <input type="text" name="name" class="form-control" id="name" maxlength="250" placeholder="{{ __('role.placeholders.name') }}" value="{{ $entity->name }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="description" class="col-sm-2 col-form-label">
                    {{ __('role.labels.description') }} <span class="text-danger">*</span>
                </label>
                <div class="col-sm-10">
                    <input type="text" name="description" class="form-control" id="description" maxlength="250" placeholder="{{ __('role.placeholders.description') }}" value="{{ $entity->description }}">
                </div>
            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <div class="row">
                <div class="col text-center">
                    <button type="button" class="btn btn-default btn-sm"
                            data-dismiss="modal">{{ __('app.labels.close') }}</button>
                    <button type="submit"
                            class="btn btn-primary btn-sm">{{ __('app.labels.save') }}</button>
                </div>
            </div>
        </div>
    </form>
</div>

<script>
    $(function () {
        const $form = $('#updateMenu')

        $validateDefaults.rules = {
            name: {
                required: true,
                minlength: 2,
                remote: {
                    url: "{!! route('checkuniquefield') !!}",
                    data: {
                        fieldName: 'name',
                        fieldValue: () => {
                            return $('#name', $form).val()
                        },
                        model: 'App\\Models\\admin\\Role',
                        current: '{{ $entity->id }}'
                    }
                }
            },
            description: {
                required: true
            }
        }

        $validateDefaults.messages = {
            name: {
                remote: '{!! trans('role.messages.validation.name') !!}'
            }
        }

        // J Validator
        $form.validate($validateDefaults);
        $form.ajaxForm($.extend(false, $formAjaxDefaults, {
            success: (response) => {
                processResponse(response, null, () => {
                    $modal.modal('hide')
                })
            }
        }))
    })
</script>
@else
    @include('errors.403_modal')
@endcan