routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'dashboard'])->name('dashboard.app');

Route::get('forgot-password-verify/{token}', [App\Http\Controllers\LoginController::class, 'forgotPasswordValidate'])->name('forgot-password-verify');
Route::post('forgot-password', [App\Http\Controllers\LoginController::class, 'resetPassword'])->name('password-send-email');
Route::put('reset-password', [App\Http\Controllers\LoginController::class, 'updatePassword'])->name('reset-password');

/* ---------------- */
/* Global Functions */
/* ---------------- */
Route::group([
    'middleware' => ['auth']
],
    function () {
        Route::get('configuration/checkuniquefield', [App\Http\Controllers\System\UtilsController::class, 'checkUniqueField'])->name('checkuniquefield');
    }
);

/* ---------------- */
/* Routes admin */
/* ---------------- */
Route::group(['middleware' => ['auth']], function() {
    // Profile
    Route::get('profile/index', [App\Http\Controllers\admin\ProfileController::class, 'index'])->name('index.profile');
    Route::get('profile/edit', [App\Http\Controllers\admin\ProfileController::class, 'edit'])->name('edit.profile');
    Route::put('profile/update/{id}', [App\Http\Controllers\admin\ProfileController::class, 'update'])->name('update.profile');
    Route::put('profile/check/email', [App\Http\Controllers\admin\ProfileController::class, 'checkEmail'])->name('email_verify.profile');
    Route::get('profile/password', [App\Http\Controllers\admin\ProfileController::class, 'changePassword'])->name('change_password.profile');
    Route::put('profile/password/{id}', [App\Http\Controllers\admin\ProfileController::class, 'updatePassword'])->name('update_password.profile');

    // Menu
    Route::get('menus/data', [App\Http\Controllers\admin\MenuController::class, 'data'])->name('menus.data');
    Route::get('menus/enable_disable/{id}', [App\Http\Controllers\admin\MenuController::class, 'enableDisable'])->name('menus.enable_disable');
    Route::resource('menus', App\Http\Controllers\admin\MenuController::class, [
        'parameters' => ['menus' => 'id'],
        'names' => [
            'show' => 'show.menus',
            'store' => 'store.menus',
            'edit' => 'edit.menus',
            'update' => 'update.menus',
            'destroy' => 'destroy.menus'
        ]
    ]);

    // Roles
    Route::get('roles/data', [App\Http\Controllers\admin\RoleController::class, 'data'])->name('roles.data');
    Route::get('roles/enable_disable/{id}', [App\Http\Controllers\admin\RoleController::class, 'enableDisable'])->name('roles.enable_disable');
    Route::get('roles/permissions/{id}', [App\Http\Controllers\admin\RoleController::class, 'permissions'])->name('roles.permissions');
    Route::resource('roles', App\Http\Controllers\admin\RoleController::class, [
        'parameters' => ['roles' => 'id'],
        'names' => [
            'show' => 'show.roles',
            'store' => 'store.roles',
            'edit' => 'edit.roles',
            'update' => 'update.roles',
            'destroy' => 'destroy.roles'
        ]
    ]);

    // Usuarios
    Route::get('users/check_email', [App\Http\Controllers\admin\UserController::class, 'checkEmailExists'])->name('check_email.users');
    Route::get('users/data', [App\Http\Controllers\admin\UserController::class, 'data'])->name('users.data');
    Route::get('users/enable_disable/{id}', [App\Http\Controllers\admin\UserController::class, 'enableDisable'])->name('users.enable_disable');
    Route::resource('users', App\Http\Controllers\admin\UserController::class, [
        'parameters' => ['users' => 'id'],
        'names' => [
            'show' => 'show.users',
            'store' => 'store.users',
            'edit' => 'edit.users',
            'update' => 'update.users',
            'destroy' => 'destroy.users'
        ]
    ]);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'username',
        'first_name',
        'last_name',
        'document_type',
        'document',
        'photo',
        'email',
        'email_verified_at',
        'password',
        'changed_password',
        'status'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Document type
     */
    const DOCUMENT_TYPE = [
        ['id' => 'CED', 'description' => 'Cédula'],
        ['id' => 'RUC', 'description' => 'RUC'],
        ['id' => 'PAS', 'description' => 'Pasaporte']
    ];

    /**
     * Get the credit request full name.
     *
     * @return string
     */
    public function fullName()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

}

app/Http/Controllers/admin/UserController.php
<?php

namespace App\Http\Controllers\admin;

use App\Repositories\admin\User\UserInterface;
use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Yajra\DataTables\DataTables;
use Illuminate\Http\Request;
use App\Models\admin\Role;
use App\Models\User;
use Exception;
use Throwable;

class UserController extends Controller
{
    protected $user;

    public function __construct(UserInterface $user)
    {
        $this->user = $user;
        // Set permissions
        $this->middleware('permission:user-list|user-create|user-edit|user-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:user-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:user-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:user-delete', ['only' => ['destroy']]);
        $this->middleware('permission:user-show', ['only' => ['show']]);
        $this->middleware('permission:user-delete', ['only' => ['delete']]);
    }

    /**
     * Index.
     *
     * @return JsonResponse
     */
    public function index()
    {
        try {
            $response['view'] = view('admin.user.index', [
                'users' => $this->user->getAllData()
            ])->render();
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * Data.
     *
     * @param Request $request
     *
     * @return void
     * @throws \Exception
     */
    public function data(Request $request)
    {
        try {
            if ($request->ajax()) {
                $user = currentUser();
                $data = User::all()->sortBy('weight');
                $actions = [];
                if ($user->can('user-edit')) {
                    $actions['edit'] = [
                        'route' => 'edit.users',
                        'tooltip' => __('user.labels.edit')
                    ];
                }
                if ($user->can('user-show')) {
                    $actions['eye'] = [
                        'route' => 'show.users',
                        'tooltip' => __('user.labels.show')
                    ];
                }
                if ($user->can('user-delete')) {
                    $actions['trash'] = [
                        'route' => 'destroy.users',
                        'tooltip' => __('app.labels.delete'),
                        'confirm_message' => __('user.messages.confirm.delete'),
                        'method' => 'delete',
                        'btn_class' => 'btn-danger'
                    ];
                }
                $disable = true;
                if ($user->can('user-enable_disable')) {
                    $disable = false;
                }
                return Datatables::of($data)
                    ->setRowId('id')
                    ->addColumn('actions', function ($entity) use ($actions) {
                        return view('layout.partial.datatable_action', [
                            'entity' => $entity,
                            'actions' => $actions
                        ]);
                    })
                    ->addColumn('full_name', function ($entity) use ($actions) {
                        return $entity->fullName();
                    })
                    ->addColumn('enabled', function ($entity) use ($user, $disable) {
                        $checked = $entity->status ? 'checked' : '';
                        $is_disable = $disable ? 'disabled' : '';
                        return "<div class='form-group text-center'>
                                    <div class='custom-control custom-switch'>
                                        <input type='checkbox' class='custom-control-input' id='customSwitch" . $entity->id . "' " . $checked . " " . $is_disable . ">
                                        <label class='custom-control-label' for='customSwitch" . $entity->id . "'></label>
                                    </div>
                                </div>";
                    })
                    ->editColumn('icon', function ($entity) {
                        $icon = $entity->icon;
                        return "<i class='fa fa-{$icon}' aria-hidden='true'></i>";
                    })
                    ->rawColumns(['actions', 'icon', 'enabled'])
                    ->make(true);
            }
        } catch (Throwable $e) {
            return datatableEmptyResponse($e);
        }
    }

    /**
     * Create.
     *
     * @return JsonResponse
     */
    public function create()
    {
        try {
            $response['modal'] = view('admin.user.create',[
                'roles' => Role::where('status', 1)->get()
            ])->render();
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * Store.
     *
     * @param Request $request
     * @return JsonResponse
     */
    public function store(Request $request)
    {
        try {
            $data = $request->only([
                'first_name',
                'last_name',
                'document_type',
                'document',
                'email',
                'username',
                'password',
                'roles',
                'photo'
            ]);
            $this->user->storeOrUpdate($id = null, $data);
            $response = [
                'view' => view('admin.user.index')->render(),
                'message' => [
                    'title' => __('app.labels.done'),
                    'type' => 'success',
                    'text' => __('user.messages.success.created')
                ]
            ];
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * Edit
     * @param int $id
     * @return JsonResponse
     */
    public function edit(int $id)
    {
        try {
            $entity = User::find($id);
            $user_roles = count($entity->roles) ? $entity->roles->pluck('id')->toArray() : [];
            $response['modal'] = view('admin.user.update', [
                'entity' => $entity,
                'roles' => Role::where('status', 1)->get(),
                'user_roles' => $user_roles
            ])->render();
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * @param int $id
     * @param Request $request
     * @return JsonResponse
     */
    public function update(int $id, Request $request)
    {
        try {
            $data = $request->only([
                'first_name',
                'last_name',
                'document_type',
                'document',
                'email',
                'username',
                'password',
                'roles',
                'photo'
            ]);
            $this->user->storeOrUpdate($id, $data);
            $response = [
                'view' => view('admin.user.index')->render(),
                'message' => [
                    'title' => __('app.labels.done'),
                    'type' => 'success',
                    'text' => __('user.messages.success.updated')
                ]
            ];
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * Show
     *
     * @param int $id
     * @return JsonResponse
     */
    public function show(int $id)
    {
        try {
            $response['modal'] = view('admin.user.show', [
                'entity' => User::find($id),
                'roles' => Role::where('status', 1)->get()
            ])->render();
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * Enable or Disable this model.
     *
     * @param $id
     *
     * @return JsonResponse
     */
    public function enableDisable($id)
    {
        try {
            $entity = User::find($id);
            if (!$entity) {
                throw new Exception(__('user.messages.exceptions.not_found'), 1000);
            }
            $entity->status = !$entity->status;
            if (!$this->user->changeStatus($entity)) {
                throw new Exception(__('user.messages.errors.update'), 1000);
            }
            $response['message'] = [
                'title' => __('app.labels.done'),
                'type' => 'success',
                'text' => __('user.messages.success.updated')
            ];
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * Destroy.
     *
     * @param $id
     *
     * @return JsonResponse
     */
    public function destroy($id)
    {
        try {
            $response = $this->user->destroy($id);
            if ($response) {
                $response = [
                    'view' => view('admin.user.index')->render(),
                    'message' => [
                        'title' => __('app.labels.done'),
                        'type' => 'success',
                        'text' => __('user.messages.success.deleted')
                    ]
                ];
            } else {
                $response = [
                    'view' => view('admin.user.index')->render(),
                    'message' => [
                        'title' => __('app.labels.error'),
                        'type' => 'alert',
                        'text' => __('user.messages.alert.delete')
                    ]
                ];
            }
        } catch (Throwable $e) {
            $response = defaultCatchHandler($e);
        }
        return response()->json($response);
    }

    /**
     * Check Email Exists.
     *

resources/views/admin/user/create.blade.php
@can('user-create')
@inject('User', '\App\Models\User')
<div class="modal-header">
    <h4 class="modal-title">{{ __('user.labels.create') }}</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form id="createMenu" role="form" action="{{ route('store.users') }}" method="post" class="form-horizontal form-label-left">
        @csrf
        <div class="card-body">
            <div class="form-group row">
                <label for="first_name" class="col-sm-3 col-form-label">
                    {{ __('user.labels.first_name') }} <span class="text-danger">*</span>
                </label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="first_name" id="first_name" maxlength="50" placeholder="{{ __('user.placeholders.first_name') }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="last_name" class="col-sm-3 col-form-label">
                    {{ __('user.labels.last_name') }} <span class="text-danger">*</span>
                </label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="last_name" id="last_name" maxlength="50" placeholder="{{ __('user.placeholders.last_name') }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="document_type" class="col-sm-3 col-form-label">
                    {{ __('user.labels.document_type') }} <span class="text-danger">*</span>
                </label>
                <div class="col-sm-9">
                    <select id="document_type" name="document_type" class="form-control select2" required>
                        <option></option>
                        @foreach($User::DOCUMENT_TYPE as $value)
                            <option value="{{ $value['id'] }}">
                                {{ $value['description'] }}
                            </option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="document" class="col-sm-3 col-form-label">
                    {{ __('user.labels.document') }} <span class="text-danger">*</span>
                </label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="document" id="document" maxlength="50" placeholder="{{ __('user.placeholders.document') }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="email" class="col-sm-3 col-form-label">
                    {{ __('user.labels.email') }}  <span class="text-danger">*</span>
                </label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="email" id="email" placeholder="{{ __('user.placeholders.email') }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="username" class="col-sm-3 col-form-label">
                    {{ __('user.labels.username') }} <span class="text-danger">*</span>
                </label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="username" id="username" placeholder="{{ __('user.placeholders.username') }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="password" class="col-sm-3 col-form-label">
                    {{ __('user.labels.password') }} <span class="text-danger">*</span>
                </label>
                <div class="col-sm-9">
                    <input type="password" class="form-control" name="password" id="password" placeholder="{{ __('user.placeholders.password') }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="repeat_password" class="col-sm-3 col-form-label">
                    {{ __('user.labels.repeat_password') }} <span class="text-danger">*</span>
                </label>
                <div class="col-sm-9">
                    <input type="password" class="form-control" name="repeat_password" id="repeat_password" placeholder="{{ __('user.placeholders.repeat_password') }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="repeat_password" class="col-sm-3 col-form-label">
                    {{ __('user.labels.roles') }} <span class="text-danger">*</span>
                </label>
                <div class="col-sm-9">
                    <select id="roles" name="roles[]" class="form-control select2" multiple required>
                        <option></option>
                        @foreach($roles as $value)
                            <option value="{{ $value->id }}">
                                {{ $value->description }}
                            </option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <div class="row">
                <div class="col text-center">
                    <button type="button" class="btn btn-default btn-sm"
                            data-dismiss="modal">{{ __('app.labels.close') }}</button>
                    <button type="submit"
                            class="btn btn-primary btn-sm">{{ __('app.labels.save') }}</button>
                </div>
            </div>
        </div>
    </form>
</div>

<script>
    $(function () {
        const $form = $('#createMenu')
        const documentType = $('#document_type')
        const document = $('#document')
        const email = $('#email')
        const userName = $('#username')

        $('.select2', $form).select2({
            placeholder: "{{ trans('app.labels.select') }}",
            width: '100%',
            theme: "classic",
            allowClear: true
        }).on("select2:close", function (e) {
            $(this).valid()
        })

        email.on('change', function () {
            userName.val(email.val())
        })

        documentType.on('change', function () {
            switch (this.value) {
                case 'CED' :
                    document.rules("remove", "passport ruc")
                    document.rules("add", {
                        cedula: true
                    })
                    break;
                case 'PAS' :
                    document.rules("remove", "cedula ruc")
                    document.rules("add", {
                        passport: true
                    })
                    break;
                case 'RUC' :
                    document.rules("remove", "cedula passport")
                    document.rules("add", {
                        ruc: true
                    })
            }
            document.valid()
        })

        $validateDefaults.rules = {
            first_name: {
                required: true,
                lettersOnly: true
            },
            last_name: {
                required: true,
                lettersOnly: true
            },
            document_type: {
                required: true
            },
            document: {
                required: true,
                remote: {
                    url: "{!! route('checkuniquefield') !!}",
                    data: {
                        fieldName: 'document',
                        fieldValue: () => {
                            return $('#document', $form).val()
                        },
                        model: 'App\\Models\\User'
                    }
                }
            },
            email: {
                required: true,
                emailChecker: true,
                remote: {
                    url: "{!! route('check_email.users') !!}",
                    data: {
                        email: function () {
                            return email.val()
                        }
                    }
                }
            },
            username: {
                required: true,
                remote: {
                    url: "{!! route('checkuniquefield') !!}",
                    data: {
                        fieldName: 'username',
                        fieldValue: () => {
                            return $('#username', $form).val()
                        },
                        model: 'App\\Models\\User'
                    }
                }
            },
            password: {
                required: true,
                minlength: 6
            },
            repeat_password: {
                required: true,
                equalTo: '#password'
            },
            roles: {
                required: true
            }
        }

        $validateDefaults.messages = {
            email: {
                remote: '{!! trans('user.messages.validation.email_exists') !!}'
            },
            username: {
                remote: '{!! trans('user.messages.validation.name') !!}'
            },
            document: {
                remote: '{!! trans('user.messages.validation.document_exists') !!}'
            }
        }

        // J Validator
        $form.validate($validateDefaults);
        $form.ajaxForm($.extend(false, $formAjaxDefaults, {
            success: (response) => {
                processResponse(response, null, () => {
                    $modal.modal('hide')
                })
            }
        }))
    })
</script>

@else
    @include('errors.403_modal')
@endcan

resources/views/admin/user/index.blade.php
@can('user-list')
    <!-- Navbar content -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{ __('user.title') }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">{{ __('app.labels.administration') }}</a></li>
                        <li class="breadcrumb-item active">{{ __('user.title') }}</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- COLOR PALETTE -->
            <div class="card card-default color-palette-box">
                <div class="card-header">
                    <h3 class="card-title">
                        <i class="fas fa-users"></i>
                        {{ __('user.title') }}
                    </h3>
                    @can('user-create')
                        <a href="{{ route('users.create') }}"
                           class="btn btn-primary bg-gradient-primary btn-sm float-right ajaxify">
                            {{ __('user.labels.create') }}
                        </a>
                    @endcan
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="user_tb" class="table table-striped table-bordered" width="100%">
                        <thead>
                        <tr>
                            <th></th>
                            <th>{{ __('user.labels.username') }}</th>
                            <th>{{ __('user.labels.first_name') }}</th>
                            <th>{{ __('user.labels.document') }}</th>
                            <th>{{ __('user.labels.email') }}</th>
                            <th>{{ __('user.labels.status') }}</th>
                            <th>{{ __('app.labels.actions') }}</th>
                        </tr>
                        </thead>
                    </table>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">&nbsp&nbsp</div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>

    <script>
        $(function () {
            let datatable = $('#user_tb').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('users.data') }}",
                columns: [
                    {data: 'id', name: 'id', visible: false, sortable: false, searchable: false, width: '0'},
                    {data: 'username', name: 'username', width: '20%', sortable: true, searchable: true},
                    {data: 'full_name', name: 'full_name', width: '20%', sortable: true, searchable: true},
                    {data: 'document', name: 'document', width: '10%', sortable: true, searchable: true},
                    {data: 'email', name: 'email', width: '25%', sortable: true, searchable: true},
                    {data: 'enabled', width: '10%', searchable: false, sortable: false},
                    {data: 'actions', width: '15%', sortable: false, searchable: false, class: 'text-center'}
                ]
            })

            $('#user_tb').on('click', 'input[type="checkbox"]', function (e) {
                e.preventDefault()
                let confirmMessage = $(this).is(':checked') ? '{{ __('user.messages.confirm.status_on') }}' : '{{ __('user.messages.confirm.status_off') }}'
                let element = $(this)
                confirmModal(confirmMessage, function () {
                    let id = element.closest('tr').attr('id')
                    let url = "{!! route('users.enable_disable', ['id' => '__ID__']) !!}"
                    url = url.replace('__ID__', id)
                    pushRequest(url, null, function () {
                        datatable.draw()
                    }, 'get', null)
                })
            })
        })
    </script>

@else
    @include('errors.403')
@endcan